# Generated by Django 2.0.13 on 2019-07-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок домашней страницы')),
                ('subtitle1', models.CharField(default='', max_length=100, verbose_name='Подзаголовок домашней страницы №1')),
                ('subtitle2', models.CharField(default='', max_length=100, verbose_name='Подзаголовок домашней страницы №2')),
                ('subtitle3', models.CharField(default='', max_length=100, verbose_name='Подзаголовок домашней страницы №3')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Адрес компании')),
                ('phone1', models.CharField(default='', max_length=20, verbose_name='Номер телефона №1')),
                ('phone2', models.CharField(default='', max_length=20, verbose_name='Номер телефона №2')),
                ('phone3', models.CharField(default='', max_length=20, verbose_name='Номер телефона №3')),
                ('mail', models.CharField(default='', max_length=100, verbose_name='Почтовый ящик компании')),
                ('video', models.FileField(upload_to='home/', verbose_name='Видео Главной Страницы')),
            ],
            options={
                'verbose_name_plural': 'Информация о сайте',
            },
        ),
    ]
