# Generated by Django 2.0.13 on 2019-07-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='video',
            field=models.FileField(null=True, upload_to='home/', verbose_name='Видео Главной Страницы'),
        ),
    ]
