# Generated by Django 2.0.13 on 2019-08-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190725_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='about',
            field=models.TextField(default='', verbose_name='Текст на странице о нас'),
        ),
    ]
