# Generated by Django 2.0.13 on 2019-07-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='category/', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('date', models.DateField(verbose_name='Дата проекта')),
                ('last_media', models.IntegerField(default=0, verbose_name='ID последнего файла')),
            ],
            options={
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, upload_to='projects/', verbose_name='Видео')),
                ('type', models.IntegerField(default=0)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name_plural': 'Медиа файлы Проектов',
            },
        ),
    ]
