# Generated by Django 2.0.13 on 2019-07-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
