# Generated by Django 2.0.13 on 2019-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('audio', models.FileField(upload_to='studio_sounds/', verbose_name='Аудио запись')),
            ],
        ),
    ]
