# Generated by Django 2.0.13 on 2019-08-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_studioaudio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studioaudio',
            options={'verbose_name_plural': 'Аудиозаписи Студии'},
        ),
        migrations.AlterField(
            model_name='studioaudio',
            name='audio',
            field=models.FileField(null=True, upload_to='studio_sounds/', verbose_name='Аудио запись'),
        ),
    ]
