# Generated by Django 2.0.13 on 2019-08-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190804_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='studio_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Изображения Студии',
            },
        ),
    ]
